/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DsseMgFNvTy
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "~/components/ui/card";
import { Label } from "~/components/ui/label";
import { Input } from "~/components/ui/input";
import { Textarea } from "~/components/ui/textarea";
import { Button } from "~/components/ui/button";

export function BugReportForm() {
  return (
    <Card className="h-screen sm:h-auto">
      <CardHeader>
        <CardTitle className="text-3xl sm:text-6xl">Bug Report Form</CardTitle>
        <CardDescription className="text-gray-500 sm:text-2xl">
          Please fill out the details below to report a bug.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="url">URL</Label>
              <Input
                id="url"
                placeholder="Enter the URL where the bug occurred"
              />
            </div>
            <div className="grid-cols-2 gap-5 sm:grid">
              <div>
                <Label htmlFor="company-name">Company Name</Label>
                <Input
                  id="company-name"
                  placeholder="Enter your company name"
                />
              </div>
              <div>
                <Label htmlFor="user-name">User Name</Label>
                <Input id="user-name" placeholder="Enter your user name" />
              </div>
            </div>
            <div className="grid-cols-2 gap-5 sm:grid">
              <div>
                <Label htmlFor="current-page">Current Page</Label>
                <Input id="current-page" placeholder="Enter the current page" />
              </div>
              <div>
                <Label htmlFor="previous-page">Previous Page</Label>
                <Input
                  id="previous-page"
                  placeholder="Enter the previous page"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="date">Date</Label>
              <Input
                id="date"
                placeholder="Enter the date when the bug occurred"
                type="date"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="description">Detailed Description</Label>
              <Textarea
                className="min-h-[100px]"
                id="description"
                placeholder="Describe the bug in detail"
              />
            </div>
            <Button className="w-full" type="submit" variant={"destructive"}>
              Submit Bug Report
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
