/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PWoj3syDk8l
 */
import { Button } from "~/components/ui/button"
import { Tabs } from "~/components/ui/tabs"

export function PlanPayDialog() {
  return (
    <Tabs>
      <div className="flex justify-between mb-4">
        <div>Basic</div>
        <div>Professional</div>
        <div>Enterprise</div>
      </div>
      <div>
        <div>
          <div className="space-y-4">
            <h2 className="text-xl font-bold">Basic</h2>
            <p className="text-zinc-500 dark:text-zinc-400">Basic access to all features</p>
            <div className="font-semibold text-lg">$10</div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="firstName">
                First Name:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="firstName"
                placeholder="Your First Name"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="lastName">
                Last Name:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="lastName"
                placeholder="Your Last Name"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="street">
                Street:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="street"
                placeholder="Your Street"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="street2">
                Street 2:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="street2"
                placeholder="Your Street 2 (Optional)"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="city">
                City:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="city"
                placeholder="Your City"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="state">
                State:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="state"
                placeholder="Your State"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="zip">
                Zip:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="zip"
                placeholder="Your Zip"
                type="text"
              />
            </div>
            <Button className="w-full" variant="default">
              Pay Now
            </Button>
          </div>
        </div>
        <div>
          <div className="space-y-4">
            <h2 className="text-xl font-bold">Professional</h2>
            <p className="text-zinc-500 dark:text-zinc-400">Professional access to all features</p>
            <div className="font-semibold text-lg">$30</div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="firstName">
                First Name:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="firstName"
                placeholder="Your First Name"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="lastName">
                Last Name:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="lastName"
                placeholder="Your Last Name"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="street">
                Street:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="street"
                placeholder="Your Street"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="street2">
                Street 2:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="street2"
                placeholder="Your Street 2 (Optional)"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="city">
                City:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="city"
                placeholder="Your City"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="state">
                State:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="state"
                placeholder="Your State"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="zip">
                Zip:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="zip"
                placeholder="Your Zip"
                type="text"
              />
            </div>
            <Button className="w-full" variant="default">
              Pay Now
            </Button>
          </div>
        </div>
        <div>
          <div className="space-y-4">
            <h2 className="text-xl font-bold">Enterprise</h2>
            <p className="text-zinc-500 dark:text-zinc-400">Enterprise access to all features</p>
            <div className="font-semibold text-lg">$50</div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="firstName">
                First Name:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="firstName"
                placeholder="Your First Name"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="lastName">
                Last Name:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="lastName"
                placeholder="Your Last Name"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="street">
                Street:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="street"
                placeholder="Your Street"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="street2">
                Street 2:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="street2"
                placeholder="Your Street 2 (Optional)"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="city">
                City:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="city"
                placeholder="Your City"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="state">
                State:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="state"
                placeholder="Your State"
                type="text"
              />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-bold mb-2" htmlFor="zip">
                Zip:
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="zip"
                placeholder="Your Zip"
                type="text"
              />
            </div>
            <Button className="w-full" variant="default">
              Pay Now
            </Button>
          </div>
        </div>
      </div>
    </Tabs>
  )
}
