/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KQuDDFbeeAY
 */
import {
  CardTitle,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "~/components/ui/card";
import { Badge } from "~/components/ui/badge";
import { Button } from "~/components/ui/button";
import Link from "next/link";
import Image from "next/image";

export function TableOfContents() {
  return (
    <section className="w-screen p-6 sm:p-12">
      <div className="grid gap-4">
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3">
          <Card className="dark:bg-white dark:text-black">
            <CardHeader>
              <CardTitle className="lg:text-2xl xl:text-3xl">
                Beach Adventures
              </CardTitle>
              <Badge className="bg-red-600 text-white">Best Seller</Badge>
            </CardHeader>
            <Image
              alt="Product 1"
              className=" w-full object-cover"
              height="200"
              src="/img/01-beach.webp"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardContent>
              <p className="beach-description pt-5 text-xl">
                This a beach adventure. It is a very nice beach. You will enjoy
                it.
              </p>
            </CardContent>
            <CardFooter>
              <Link href="#">
                <Button variant={"destructive"}>View More</Button>
              </Link>
            </CardFooter>
          </Card>
          <Card className="dark:bg-white dark:text-black">
            <CardHeader>
              <CardTitle className="lg:text-2xl xl:text-3xl">
                Mountain adventure
              </CardTitle>
              <Badge className="bg-blue-600 text-white">New Arrival</Badge>
            </CardHeader>
            <Image
              alt="Mountain adventure"
              className="w-full object-cover"
              height="200"
              src="/img/02-mountains.webp"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardContent>
              <p className="pt-5 text-xl">This is Mountain adventure.</p>
            </CardContent>
            <CardFooter>
              <Link href="#">
                <Button variant={"destructive"}>View More</Button>
              </Link>
            </CardFooter>
          </Card>
          <Card className="dark:bg-white dark:text-black">
            <CardHeader>
              <CardTitle className="lg:text-2xl xl:text-3xl">
                City Adventure
              </CardTitle>
              <Badge className="bg-black text-white">Featured</Badge>
            </CardHeader>
            <Image
              alt="City Adventure"
              className="w-full object-cover"
              height="200"
              src="/img/03-city.webp"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardContent>
              <p className="pt-5 text-xl ">This is City Adventure.</p>
            </CardContent>
            <CardFooter>
              <Link href="#">
                <Button variant={"destructive"}>View More</Button>
              </Link>
            </CardFooter>
          </Card>
        </div>
      </div>
    </section>
  );
}
